// app/layout.tsx
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { SessionProvider } from "next-auth/react"; // ۱. SessionProvider را وارد کنید
import { auth } from "@/lib/auth"; // ۲. auth را برای گرفتن session وارد کنید
import "./globals.css";
import Navbar from "@/components/Navbar";
import AddCardFab from "@/components/AddCardFab"; // <-- وارد کردن کامپوننت


const vazir = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazir",
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ۳. وضعیت کاربر را در سرور بگیرید
  const session = await auth();

  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazir.variable} font-sans antialiased`}>
        {/* ۴. کل برنامه را با SessionProvider بپوشانید و session را به آن پاس دهید */}
        <SessionProvider session={session}>
          <Navbar />
          {children}
          {session?.user && <AddCardFab />}
        </SessionProvider>
      </body>
    </html>
  );
}