// app/layout.tsx
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";
import "./globals.css";

const vazir = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazir",
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Leitner System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazir.variable} font-sans antialiased bg-gray-900 text-white`}>
        {/* bg-gray-900 -> پس‌زمینه دارک
            text-white -> متن پیش‌فرض روشن */}
        <SessionProvider session={session}>
   
          {children}
         
        </SessionProvider>
      </body>
    </html>
  );
}
